# Generated by Django 5.0.6 on 2024-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=25000, max_digits=32, unique=True, verbose_name='Цена'),
        ),
    ]
