# Generated by Django 5.0.6 on 2024-05-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amount',
        ),
    ]
