# Generated by Django 5.0.6 on 2024-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=32, verbose_name='Общая сумма'),
        ),
    ]
